[package]
name = "plotters-dioxus"
version = "0.1.0"
edition = "2024"
resolver = "1"

[dependencies]
dioxus.workspace = true
plotters.workspace = true
base64 = "0.22.1"
plotters-bitmap = "0.3.3"
flow-plots.workspace = true
flow-fcs.workspace = true